# Generated by Django 5.0 on 2025-06-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.CharField(max_length=10, unique=True)),
                ('last_refresh', models.DateTimeField(auto_now=True)),
                ('total_symbols', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'symbol_refresh_logs',
            },
        ),
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('exchange_code', models.CharField(db_index=True, max_length=10)),
                ('exchange_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('type', models.CharField(default='Common Stock', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_symbols',
                'indexes': [models.Index(fields=['symbol'], name='stock_symbo_symbol_771c39_idx'), models.Index(fields=['name'], name='stock_symbo_name_ca2eb1_idx'), models.Index(fields=['exchange_code'], name='stock_symbo_exchang_6c18c4_idx'), models.Index(fields=['symbol', 'exchange_code'], name='stock_symbo_symbol_83cb6a_idx')],
            },
        ),
    ]
