# Generated by Django 5.0 on 2025-06-20 10:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolios',
                'indexes': [models.Index(fields=['user_id'], name='portfolios_user_id_f89dea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('used_cash_balance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='api.portfolio')),
            ],
            options={
                'db_table': 'holdings',
            },
        ),
        migrations.CreateModel(
            name='CashContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contribution_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_contributions', to='api.portfolio')),
            ],
            options={
                'db_table': 'cash_contributions',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dividend_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.portfolio')),
            ],
            options={
                'db_table': 'portfolio_snapshots',
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('alert_type', models.CharField(choices=[('above', 'Price Above'), ('below', 'Price Below')], max_length=10)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='api.portfolio')),
            ],
            options={
                'db_table': 'price_alerts',
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('amount_per_share', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confirmed_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='api.holding')),
            ],
            options={
                'db_table': 'dividend_payments',
                'indexes': [models.Index(fields=['holding', 'ex_date'], name='dividend_pa_holding_58130f_idx'), models.Index(fields=['payment_date'], name='dividend_pa_payment_da1a9c_idx'), models.Index(fields=['confirmed_received'], name='dividend_pa_confirm_bc0389_idx')],
                'unique_together': {('holding', 'ex_date')},
            },
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio', 'ticker'], name='holdings_portfol_527079_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['ticker'], name='holdings_ticker_08d63f_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['purchase_date'], name='holdings_purchas_b62e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashcontribution',
            index=models.Index(fields=['portfolio', 'contribution_date'], name='cash_contri_portfol_ee5f39_idx'),
        ),
        migrations.AddIndex(
            model_name='cashcontribution',
            index=models.Index(fields=['contribution_date'], name='cash_contri_contrib_4d92de_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['portfolio', 'snapshot_date'], name='portfolio_s_portfol_24b4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['snapshot_date'], name='portfolio_s_snapsho_ed5790_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('portfolio', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['portfolio', 'is_active'], name='price_alert_portfol_ee04ec_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['ticker', 'is_active'], name='price_alert_ticker_d5b8bf_idx'),
        ),
    ]
