# Generated by Django 4.2.23 on 2025-06-21 00:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio_holding_cashcontribution_portfoliosnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='holding',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=15),
        ),
    ]
