# Generated by Django 4.2.23 on 2025-06-21 03:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_holding_currency_holding_fx_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close', models.DecimalField(decimal_places=6, max_digits=15)),
                ('adjusted_close', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('dividend_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cached_daily_prices',
                'indexes': [models.Index(fields=['symbol', 'date'], name='cached_dail_symbol_2419c0_idx'), models.Index(fields=['date'], name='cached_dail_date_2fd297_idx'), models.Index(fields=['symbol'], name='cached_dail_symbol_531ea7_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CachedCompanyFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_updated', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cached_company_fundamentals',
                'indexes': [models.Index(fields=['symbol'], name='cached_comp_symbol_a3fb3d_idx'), models.Index(fields=['last_updated'], name='cached_comp_last_up_d59f3d_idx')],
            },
        ),
    ]
