# Generated by Django 4.2.7 on 2025-06-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cacheddailyprice_cachedcompanyfundamentals'),
    ]

    operations = [
    ]
