# Generated by Django 4.2.23 on 2025-06-22 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250622_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('last_price_fetch', models.DateTimeField(blank=True, null=True)),
                ('fetch_count_today', models.IntegerField(default=0)),
                ('daily_limit', models.IntegerField(default=100)),
                ('rate_limit_exceeded', models.BooleanField(default=False)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_user_rate_limit',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('display_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won')], default='USD', max_length=3)),
                ('show_currency_conversion', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('default_transaction_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_user_settings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend')], max_length=10)),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price_per_share', models.DecimalField(decimal_places=6, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('transaction_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won')], default='USD', max_length=3)),
                ('fx_rate_to_usd', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('daily_volume', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('used_cash_balance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_transaction',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'ticker'], name='api_transac_user_id_b5e4fe_idx'), models.Index(fields=['user_id', 'transaction_date'], name='api_transac_user_id_fc7bd7_idx'), models.Index(fields=['ticker', 'transaction_date'], name='api_transac_ticker_7fe561_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('date', models.DateField()),
                ('source', models.CharField(default='ECB', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_exchange_rate',
                'indexes': [models.Index(fields=['base_currency', 'target_currency', 'date'], name='api_exchang_base_cu_a791aa_idx')],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('adjusted_close', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(default='AlphaVantage', max_length=50)),
                ('requested_by_user', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_daily_price_cache',
                'indexes': [models.Index(fields=['ticker', 'date'], name='api_daily_p_ticker_f4b074_idx'), models.Index(fields=['ticker'], name='api_daily_p_ticker_029314_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
