# Generated by Django 4.2.7 on 2025-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userapiratelimit_usersettings_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
