import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://portfoliotracker.com'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/auth',
          '/dashboard',
          '/portfolio',
          '/analytics', 
          '/research',
          '/watchlist',
          '/transactions',
          '/settings',
          '/privacy',
          '/terms',
          '/security',
          '/help',
          '/contact',
          '/api',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/temp/',
          '/private/',
          '*.json',
          '/auth/callback',
          '/auth/verify-email',
          '/settings/account/delete',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/auth',
          '/dashboard',
          '/portfolio',
          '/analytics',
          '/research',
          '/watchlist',
          '/transactions',
          '/settings',
          '/privacy',
          '/terms',
          '/security',
          '/help',
          '/contact',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/temp/',
          '/private/',
          '/auth/callback',
          '/auth/verify-email',
          '/settings/account/delete',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/auth',
          '/dashboard',
          '/portfolio',
          '/analytics',
          '/research',
          '/watchlist',
          '/transactions',
          '/settings',
          '/privacy',
          '/terms',
          '/security',
          '/help',
          '/contact',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/temp/',
          '/private/',
          '/auth/callback',
          '/auth/verify-email',
          '/settings/account/delete',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}