version: '3.8'

services:
  backend:
    build: 
      context: ./backend_simplified
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - env.test
    environment:
      - SUPA_API_URL=${SUPA_API_URL}
      - SUPA_API_ANON_KEY=${SUPA_API_ANON_KEY}
      - SUPA_API_SERVICE_KEY=${SUPA_API_SERVICE_KEY}
      - VANTAGE_API_KEY=${VANTAGE_API_KEY}
      - BACKEND_API_PORT=8000
      - BACKEND_API_HOST=0.0.0.0
      - BACKEND_API_DEBUG=true
      - LOG_LEVEL=INFO

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - env.test
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=${SUPA_API_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPA_API_ANON_KEY}
    depends_on:
      - backend
    command: npm run dev 