name: Quality Gate Enforcement

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_quality_checks:
        description: 'Skip quality gate checks'
        required: false
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'

env:
  SKIP_QUALITY_CHECKS: ${{ github.event.inputs.skip_quality_checks || 'false' }}

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install monitoring dependencies
      run: |
        pip install mypy
        npm install -g jscpd type-coverage
    
    - name: Install project dependencies
      run: |
        cd frontend && npm install
        # Add backend dependency installation if needed
    
    - name: Check for skip file
      id: skip_check
      run: |
        if [ -f "SKIP_QUALITY_CHECKS" ]; then
          echo "skip_found=true" >> $GITHUB_OUTPUT
          echo "⚠️ Found SKIP_QUALITY_CHECKS file - quality checks will be skipped"
        else
          echo "skip_found=false" >> $GITHUB_OUTPUT
        fi

    - name: Run Quality Gate Check
      if: env.SKIP_QUALITY_CHECKS != 'true' && steps.skip_check.outputs.skip_found != 'true'
      run: python scripts/ci_quality_gate.py --strict
      
    - name: Skip Quality Gate (Warning)
      if: env.SKIP_QUALITY_CHECKS == 'true' || steps.skip_check.outputs.skip_found == 'true'
      run: |
        echo "⚠️ WARNING: Quality gate checks have been SKIPPED!"
        if [ "${{ steps.skip_check.outputs.skip_found }}" == "true" ]; then
          echo "Reason: SKIP_QUALITY_CHECKS file found in repository root"
          echo "To re-enable: Delete the SKIP_QUALITY_CHECKS file"
        else
          echo "Reason: Manual workflow trigger with skip option"
        fi
        echo "This should only be used for emergencies or hotfixes."
        echo "Please re-enable quality checks for normal development."
    
    - name: Upload Quality Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-report
        path: |
          metrics/ci_quality_report.json
          metrics/quality_gate_junit.xml
          quality_dashboard.html
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Quality Gate Results
        path: metrics/quality_gate_junit.xml
        reporter: java-junit
